/**
 * @file Fenetre.java
 * @brief classe pour pour lancer l'application
 * @author Stefan (devgit@factooor.fr)
 * @date 22 mai 2012
 * @version 1.0
 * @details cette classe contient toutes les fontions pour utiliser le programme
 *          sauf les foncitons de connection à la base de données sqlite
 */


package Interface;

import java.awt.Color;
import java.awt.Component;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class Fenetre extends javax.swing.JFrame {
    /**
    * @brief Déclaration et initialisation des variables 
    */
    private String requete = "";
    private String T;
    private String TVA;
    private String TVAT;
    private String TTC;
    private String HT;
    private Component tableau;
    
    Connection connex = null;
    ResultSet rs = null;
    PreparedStatement pstm = null;
    /**
     * @brief Création de l'interface et gére le lancement et le placement
     * @details Lance l'initialisation des composants et le placmeent de 
     * l'interface au centre de l'écran. 
     * @param setBounds(0, 0, 1045, 780) Correspond aux entrées de \a X, de 
     * \a Y, \a Largeur et \a Hauteur.
     * @param setBackground(Color.WHITE) (FFFFFF) Met la couleur \a Blanche 
     * en fond.
     * @param setLocationRelativeTo(this.getParent()) Centre par rapport
     * à l'écran.
     */
    public Fenetre() {
        initComponents();
        this.setBounds(0x0, 0x0, 960, 795);
        this.setLocationRelativeTo(this.getParent());/*!  */               
        this.setBackground(Color.WHITE);
        LancerApllication(); /*!Appel la fonction \a LancerApllication()*/
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupeBtn = new javax.swing.ButtonGroup();
        jPanelHaut = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jformaIdRecu = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboEnseigne = new javax.swing.JComboBox();
        TextRs = new javax.swing.JTextField();
        TextVille = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboDesi = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteAera = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        MontantHT = new javax.swing.JFormattedTextField();
        MontantTva = new javax.swing.JFormattedTextField();
        MontantTTC = new javax.swing.JFormattedTextField();
        jComboModePa = new javax.swing.JComboBox();
        jComboToTva = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBValider = new javax.swing.JButton();
        jBMaj = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TxtRecherche = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboEnse = new javax.swing.JComboBox();
        jComboRecherche = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ChooserAnnee = new com.toedter.calendar.JYearChooser();
        jLabel24 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        TVA1 = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        TVA2 = new javax.swing.JFormattedTextField();
        TVA3 = new javax.swing.JFormattedTextField();
        TVA4 = new javax.swing.JFormattedTextField();
        TVA5 = new javax.swing.JFormattedTextField();
        TVA6 = new javax.swing.JFormattedTextField();
        TVA7 = new javax.swing.JFormattedTextField();
        TVA8 = new javax.swing.JFormattedTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        TVA9 = new javax.swing.JFormattedTextField();
        TVA10 = new javax.swing.JFormattedTextField();
        TVA11 = new javax.swing.JFormattedTextField();
        TVA12 = new javax.swing.JFormattedTextField();
        jLabel31 = new javax.swing.JLabel();
        Stotaltva196 = new javax.swing.JFormattedTextField();
        Stotaltva7 = new javax.swing.JFormattedTextField();
        Stotaltva55 = new javax.swing.JFormattedTextField();
        jLabel32 = new javax.swing.JLabel();
        tvaAnnuel = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        EnseiText = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        SireText = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        TvaText = new javax.swing.JTextField();
        ValiderBtn = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        A = new javax.swing.JTextField();
        B = new javax.swing.JTextField();
        C = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FACTOOOR NOTES");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1020, 785));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelHaut.setBackground(new java.awt.Color(102, 153, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrez les informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel2.setText("Ticket Achat N°");

        jLabel3.setText("Votre enseigne");

        jformaIdRecu.setBorder(null);
        jformaIdRecu.setEditable(false);
        jformaIdRecu.setText("0");
        jformaIdRecu.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jformaIdRecu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jformaIdRecuActionPerformed(evt);
            }
        });

        jLabel4.setText("Raison sociale");

        jLabel5.setText("Ville ");

        jLabel6.setText("Date   ");

        jLabel7.setText("Désignation   ");

        jLabel8.setText("Note  ");

        jComboEnseigne.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Votre choix ?" }));
        jComboEnseigne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEnseigneActionPerformed(evt);
            }
        });

        TextRs.setText("Renseignez ici");
        TextRs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextRsFocusGained(evt);
            }
        });

        TextVille.setText("Renseignez  la ville");
        TextVille.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextVilleFocusGained(evt);
            }
        });

        jComboDesi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Votre choix ?", "Course", "Essence", "Péage", "Restaurant", "Avion", "Train", "Taxis", "Hôtel", "Metro", "RER", "Bus", "Location", "Remboursement", "Divers", "Môtel", "Relais & Chateaux", "Chambre d'hôte", "Supermarché", "Hypermarché", "Epicerie", "Repas", "En nature", "Cadeau" }));

        noteAera.setColumns(20);
        noteAera.setRows(5);
        jScrollPane1.setViewportView(noteAera);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextVille, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jformaIdRecu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextRs, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboEnseigne, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jComboDesi, 0, 162, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jformaIdRecu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboEnseigne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextRs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboDesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Entres les montants"));

        jLabel16.setText("Montant HT ");

        jLabel17.setText("Montant TVA");

        jLabel18.setText("Montant TTC");

        jLabel19.setText("Mode de payement ");

        MontantHT.setText("0.0");
        MontantHT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MontantHTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MontantHTFocusLost(evt);
            }
        });
        MontantHT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MontantHTKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MontantHTKeyReleased(evt);
            }
        });

        MontantTva.setEditable(false);
        MontantTva.setText("0.0");

        MontantTTC.setText("0.0");
        MontantTTC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MontantTTCFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MontantTTCFocusLost(evt);
            }
        });
        MontantTTC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MontantTTCKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MontantTTCKeyReleased(evt);
            }
        });

        jComboModePa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Espèce", "Carte Bancaire", "Chèque", "Traite", "Virement", "Prélevement" }));

        jComboToTva.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "21.2", "19.6", "8.5", "7", "5.5", "2.1", "0" }));
        jComboToTva.setSelectedIndex(6);
        jComboToTva.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboToTvaItemStateChanged(evt);
            }
        });

        jLabel23.setText("Choix Taux TVA ?");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MontantTTC)
                    .addComponent(MontantTva, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboToTva, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MontantHT, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboModePa, 0, 115, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(MontantHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboToTva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(MontantTva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MontantTTC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jComboModePa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jBValider.setBackground(new java.awt.Color(51, 51, 51));
        jBValider.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBValider.setForeground(new java.awt.Color(255, 255, 255));
        jBValider.setText("VALIDER");
        jBValider.setOpaque(false);
        jBValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBValiderActionPerformed(evt);
            }
        });

        jBMaj.setBackground(new java.awt.Color(58, 200, 223));
        jBMaj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBMaj.setText("Mise à jour");
        jBMaj.setToolTipText("Dans le composant ci dessous vous pouvez modifier les données en cliquant sur dans une cellule.");
        jBMaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBMaj, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jBValider, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBValider, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMaj, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Notes", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Faites une recherche."));

        jLabel9.setText("Entête pour la recherche     ");

        TxtRecherche.setText("%");
        TxtRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtRechercheKeyReleased(evt);
            }
        });

        jLabel11.setText("Sur quelle enseigne ?");

        jComboEnse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Votre Choix ?" }));
        jComboEnse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboEnseItemStateChanged(evt);
            }
        });
        jComboEnse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEnseActionPerformed(evt);
            }
        });

        jComboRecherche.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Votre Choix ?", "MonEnseigne", "RaisonSociale", "Ville", "Date", "Designation", "Note", "TauxTva", "MontantHt", "MontantTva", "MontantTtc", "ModePayement" }));

        jLabel12.setText("Terme à rechercher ...");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboEnse, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtRecherche)
                    .addComponent(jComboRecherche, 0, 138, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboEnse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulter les notes de frais", jPanel2);

        ChooserAnnee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ChooserAnneeFocusLost(evt);
            }
        });
        ChooserAnnee.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ChooserAnneePropertyChange(evt);
            }
        });

        jLabel24.setText("Selectionnez l'année :");

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Résultat par Taux de TVA !"));
        jPanel14.setOpaque(false);

        jLabel10.setText("1 er trimestre");

        jLabel25.setText("19,6 %");

        TVA1.setEditable(false);
        TVA1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤¤#,##0.00"))));
        TVA1.setText("0.0");

        jLabel26.setText("2 e trimestre");

        jLabel27.setText("3 e trimestre");

        jLabel28.setText("4 e trimestre");

        TVA2.setEditable(false);

        TVA3.setEditable(false);

        TVA4.setEditable(false);

        TVA5.setEditable(false);

        TVA6.setEditable(false);

        TVA7.setEditable(false);

        TVA8.setEditable(false);
        TVA8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TVA8ActionPerformed(evt);
            }
        });

        jLabel29.setText("7 %");

        jLabel30.setText("5.5%");

        TVA9.setEditable(false);

        TVA10.setEditable(false);

        TVA11.setEditable(false);

        TVA12.setEditable(false);

        jLabel31.setText("S/Total");

        Stotaltva196.setEditable(false);

        Stotaltva7.setEditable(false);

        Stotaltva55.setEditable(false);

        jLabel32.setText("Total TVA");

        tvaAnnuel.setEditable(false);
        tvaAnnuel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        tvaAnnuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvaAnnuelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tvaAnnuel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(201, 201, 201))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(TVA1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TVA2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TVA3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TVA4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Stotaltva196, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel14Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel25)))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TVA5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TVA6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TVA7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TVA8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Stotaltva7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TVA9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TVA10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TVA11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TVA12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Stotaltva55, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(389, Short.MAX_VALUE))))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10))
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TVA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TVA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TVA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel27))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TVA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel28))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Stotaltva196, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel31)))
                        .addGroup(jPanel14Layout.createSequentialGroup()
                            .addComponent(jLabel30)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TVA9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TVA10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TVA11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TVA12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Stotaltva55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TVA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TVA6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TVA7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TVA8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Stotaltva7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tvaAnnuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChooserAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ChooserAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulter l'exercice", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Votre raison sociale ?"));
        jPanel11.setOpaque(false);

        jLabel20.setText("Enseigne : ");

        EnseiText.setText("Renseignez obligatoirement ici");

        jLabel21.setText("Siret/sirent : ");

        SireText.setText("53010628500014");

        jLabel22.setText("TVA   : ");

        TvaText.setText("FR 84530106285");

        ValiderBtn.setText("Valider");
        ValiderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TvaText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnseiText, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(ValiderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SireText))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnseiText)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SireText)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TvaText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(ValiderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Affichage."));
        jPanel12.setOpaque(false);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(C)
                    .addComponent(A, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(B))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion base données"));
        jPanel13.setOpaque(false);

        jButton3.setText("Exportez votre base");

        jButton5.setText("Importez vos données");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(26, 26, 26)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(409, 409, 409))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(134, 134, 134))
        );

        jTabbedPane1.addTab("Configuration", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Aide", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("FACTOOOR ?", jPanel6);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/logoFactG+.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelHautLayout = new javax.swing.GroupLayout(jPanelHaut);
        jPanelHaut.setLayout(jPanelHautLayout);
        jPanelHautLayout.setHorizontalGroup(
            jPanelHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanelHautLayout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelHautLayout.setVerticalGroup(
            jPanelHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHautLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHaut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHaut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jformaIdRecuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jformaIdRecuActionPerformed
        affichageIdrecu();
    }//GEN-LAST:event_jformaIdRecuActionPerformed

    private void jComboEnseigneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEnseigneActionPerformed
        jComboEnseigne.removeAll();
        requeteComboEnseigne();
    }//GEN-LAST:event_jComboEnseigneActionPerformed

    private void ValiderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderBtnActionPerformed
        requete = "INSERT INTO raisonSoc(MonEnseigne, Siret, TVARS)"
                + " VALUES ('" + EnseiText.getText() + "','" + SireText.getText() + "','" + TvaText.getText() + "')";
        try {
            Connection connex = SourceDonneesSqlite.getConnection();
            Statement stmt = connex.createStatement();
            //resultats = stmt.executeQuery(requete);
            if ("".equals(EnseiText.getText())) {
                erreur Erreur = new erreur();
                Erreur.setVisible(true);
            } else {
                stmt.executeUpdate(requete);
                razconfig();
                requeteComboEnseigne();
            }
            connex.close();
        } catch (SQLException e) {
            System.out.println("Erreur:Anomalie lors de l'execution de la requête : " + e);
            // arret("Anomalie lors de l'execution de la requête");
        }
    }//GEN-LAST:event_ValiderBtnActionPerformed

    private void TextRsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextRsFocusGained
        TextRs.setText("");
    }//GEN-LAST:event_TextRsFocusGained

    private void TextVilleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextVilleFocusGained
        TextVille.setText("");
    }//GEN-LAST:event_TextVilleFocusGained
        // Fin des actions sur le groupe de bouton TVA
    private void MontantHTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MontantHTFocusGained
        MontantHT.setText("");
    }//GEN-LAST:event_MontantHTFocusGained

    private void MontantHTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MontantHTFocusLost
        appelTvaTtc();
    }//GEN-LAST:event_MontantHTFocusLost

    private void MontantHTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontantHTKeyPressed
        if (evt.getKeyCode() ==10) {
            appelTvaTtc();
        }
    }//GEN-LAST:event_MontantHTKeyPressed

    private void MontantHTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontantHTKeyReleased
       if (evt.getKeyCode() ==10) {
            appelTvaTtc();
        }
    }//GEN-LAST:event_MontantHTKeyReleased

    private void MontantTTCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MontantTTCFocusGained
       MontantTTC.setText("");
       //MontantHT.setText("");
    }//GEN-LAST:event_MontantTTCFocusGained

    private void MontantTTCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MontantTTCFocusLost
        appelTVA();
        appelHT();
    }//GEN-LAST:event_MontantTTCFocusLost

    private void MontantTTCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontantTTCKeyPressed
       if (evt.getKeyCode() ==10) {
            appelTVA();
            appelHT();
        }
    }//GEN-LAST:event_MontantTTCKeyPressed

    private void MontantTTCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontantTTCKeyReleased
       if (evt.getKeyCode() ==10) {
            appelTVA();
            appelHT();
        }
    }//GEN-LAST:event_MontantTTCKeyReleased

    private void jBValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBValiderActionPerformed
        //creation et execution de la requête
        //Appel de la fonction calcul taux TVA
        String toTva = calcul(T);
        // String sqlDate = afficheDate(bonneDate); En attente de regler l'erreur.
        java.util.Date DateChoix = jDateChooser1.getDate();//new java.util.Date();    
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd MM yyyy", Locale.FRANCE);
        java.sql.Date sqlDate = new java.sql.Date(DateChoix.getTime());
        //garde en mémoire les lignes Résultant de l'éxecution de la requete
        //Création d'un statement et d'une requête sur la table recu
        requete = "INSERT INTO recu (MonEnseigne, RaisonSociale, Ville, Date, Designation, Note, TauxTva, MontantHt, MontantTva, MontantTtc, ModePayement ) values( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) " ;
            try {
                Connection connex = SourceDonneesSqlite.getConnection();
                pstm = connex.prepareStatement(requete);
                pstm.setObject(1, jComboEnseigne.getSelectedItem());
                pstm.setString(2, TextRs.getText());
                pstm.setString(3, TextVille.getText());
                pstm.setString(4, dateFormat.format(sqlDate));
                pstm.setObject(5, jComboDesi.getSelectedItem());
                pstm.setString(6, noteAera.getText());
                pstm.setObject(7, jComboToTva.getSelectedItem());
                pstm.setString(8, MontantHT.getText());
                pstm.setObject(9, MontantTva.getText());
                pstm.setString(10, MontantTTC.getText());
                pstm.setObject(11, jComboModePa.getSelectedItem());
                pstm.execute();
                //Ferme la connexion
                pstm.close();
                affichageIdrecu();
                raz();
                lancerTauxTVA();
                ouverture_jtable1();
                ouverture_jtable2();
                //actionjTable();
                /*} catch (ClassNotFoundException ex) {
                Logger.getLogger(fenetre.class.getName()).log(Level.SEVERE, null, ex);*/
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            }
    }//GEN-LAST:event_jBValiderActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Connection connex = SourceDonneesSqlite.getConnection();
        ouverture_jtable1();
        ouverture_jtable2();
    }//GEN-LAST:event_formWindowOpened

    private void jBMajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMajActionPerformed
        requete = "update recu set  MonEnseigne = ?, RaisonSociale = ?, Ville = ?, Date = ?, Designation = ?, Note = ?,  TauxTva = ?, MontantHt = ?, MontantTva = ?, MontantTtc = ?, ModePayement = ? where idRecu = ? ";
        
        try{
            Connection connex = SourceDonneesSqlite.getConnection();
            pstm = connex.prepareStatement(requete);
            pstm.setObject(1, jComboEnseigne.getSelectedItem()); // Enseigne
            pstm.setString(2, TextRs.getText());
            pstm.setString(3, TextVille.getText());
            pstm.setObject(4, jDateChooser1.getDate());//jDateChooser1
            pstm.setObject(5, jComboDesi.getSelectedItem());       
            pstm.setString(6, noteAera.getText());
            pstm.setObject(7, jComboToTva.getSelectedItem());
            pstm.setString(8, MontantHT.getText());
            pstm.setString(9, MontantTva.getText());
            pstm.setString(10,MontantTTC.getText());
            pstm.setObject(11, jComboModePa.getSelectedItem());//jComboModePa.getSelectedItem()
            pstm.setString(12, jformaIdRecu.getText()); // idrecu
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(null, "Mise à jour réussi !");
            ouverture_jtable1();
            ouverture_jtable2();
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jBMajActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            int row = jTable1.getSelectedRow();
            jformaIdRecu.setText(jTable1.getModel().getValueAt(row, 0).toString());
            jComboEnseigne.setSelectedItem(jTable1.getModel().getValueAt(row, 1).toString());
            TextRs.setText(jTable1.getModel().getValueAt(row, 2).toString());
            TextVille.setText(jTable1.getModel().getValueAt(row, 3).toString());
            jDateChooser1.setDateFormatString(jTable1.getModel().getValueAt(row, 4).toString());
            jComboDesi.setSelectedItem(jTable1.getModel().getValueAt(row, 5).toString());
            noteAera.setText(jTable1.getModel().getValueAt(row, 6).toString());
            jComboToTva.setSelectedItem(jTable1.getModel().getValueAt(row, 7).toString());
            MontantHT.setText(jTable1.getModel().getValueAt(row, 8).toString());
            MontantTva.setText(jTable1.getModel().getValueAt(row, 9).toString());
            MontantTTC.setText(jTable1.getModel().getValueAt(row, 10).toString());
            jComboModePa.setSelectedItem(jTable1.getModel().getValueAt(row, 11).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboToTvaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboToTvaItemStateChanged
        calcul(T);
        int composant = evt.getStateChange();
        if (evt.getStateChange() ==10) {
            calcul(T);
            appelTvaTtc();
           
        }else {
            appelTVA();
            appelHT();
        }
    
        appelTvaTtc();
    }//GEN-LAST:event_jComboToTvaItemStateChanged

    private void ChooserAnneeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ChooserAnneeFocusLost
        //totalannuelTVA();
    }//GEN-LAST:event_ChooserAnneeFocusLost

    private void ChooserAnneePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ChooserAnneePropertyChange
        //totalannuelTVA();
        //requetteTrimTVA();
    }//GEN-LAST:event_ChooserAnneePropertyChange

    private void TVA8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TVA8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TVA8ActionPerformed

    private void tvaAnnuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvaAnnuelActionPerformed
       // totalannuelTVA();
       // requetteTrimTVA();
    }//GEN-LAST:event_tvaAnnuelActionPerformed

    private void TxtRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRechercheKeyReleased
        Object rech = jComboRecherche.getSelectedItem(); //" + rech + "
        Object Ense = jComboEnse.getSelectedItem();
        //System.out.println("Erreur : Anomalie lors de l'execution de la requête : " + rech);
        requete = " select * from recu where "  + rech + " like ?";
        try{
            Connection connex = SourceDonneesSqlite.getConnection();
            pstm = connex.prepareStatement(requete);
            pstm.setString(1, TxtRecherche.getText() + "%");
            rs = pstm.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (Exception e){
           // JOptionPane.showMessageDialog(null, e);
            System.out.println("Erreur : Anomalie lors de l'execution de la requête : " + e);
        }
    }//GEN-LAST:event_TxtRechercheKeyReleased

    private void jComboEnseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboEnseItemStateChanged
       
    }//GEN-LAST:event_jComboEnseItemStateChanged

    private void jComboEnseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEnseActionPerformed
         jComboEnse.removeAll();
        requeteComboEnseigneRecherche();
    }//GEN-LAST:event_jComboEnseActionPerformed
    
    //-------------------------//
    /////////////////////////////
    //  Début de mes fonctions  /
    //  qui sont appelées par   /
    //  les méthodes - actions /
    /////////////////////////////
    /**
     *@brief
     * 
     */
    //01
    private void LancerApllication() {
        affichageIdrecu();
       // majJcomboBox();
        affichageEnseigne();
        requeteComboEnseigne();
        requeteComboEnseigneRecherche();
        //lancerTauxTVA();
        //totalannuelTVA();
        monLogo();
        jDateChooser1.setDate(new java.util.Date());
    }
    
    /**
     * @brief affiche le numéro
     * @details le numéro vient d'une requete sql, Compare si la table à un 
     * enregistrement à l'ouverture, Si nul alors mettre 1 dans le composant.
     */
    //02
    private void affichageIdrecu(){   
        requete = "select max(idRecu)+1 from recu"; //last_insert_rowid()
        //Stocke et garde en mémoire la requete SQL
        try {
            Connection con = SourceDonneesSqlite.getConnection();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(requete); 
            // Si nul alors mettre 1 dans le composant.
            if (rs.getString(1) == null){
            jformaIdRecu.setText("1"); 
            }else {
                //Sinon afficher le n° d'id de la table recu
            jformaIdRecu.setText(rs.getString(1));
            }
            // ferme la connection
            rs.close();               
        }catch (SQLException ex) {                       
        }       
    }
    /**
     * @brief
     */
    //03
    private void majJcomboBox(){
        jComboEnseigne.updateUI();
        if (ValiderBtn.isValidateRoot()){
            System.out.println("combobox");
            jComboEnseigne.updateUI();
            requeteComboEnseigne();
            requeteComboEnseigneRecherche();
        }
    }            
     /**
      * @Details Cette requete envoye son résultat dans un comboBox qui
      * permettra de selectionner, dans quelle entreprise vous voulez insérer
      * votre note de frais
      */
    //04
    private void requeteComboEnseigne(){
         /*! supprime tout dans le composant*/
        requete = "SELECT MonEnseigne FROM `raisonSoc`"; 
        try {
             Connection con = SourceDonneesSqlite.getConnection();
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(requete);    
                while (rs.next()) {
                jComboEnseigne.addItem(rs.getString(1));
                }
            rs.close();
        } catch (Exception e) {
            System.out.println("Erreur:Anomalie lors de l'execution de la requête : " + e);
        }
    }
    
    //04.1
    private void requeteComboEnseigneRecherche(){

       requete = "SELECT idRais, MonEnseigne FROM `raisonSoc`"; 
        try {
             Connection con = SourceDonneesSqlite.getConnection();
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(requete);    
                while (rs.next()) {
                jComboEnse.addItem(rs.getString(2));
                }
            rs.close();
        } catch (Exception e) {
            System.out.println("Erreur:Anomalie lors de l'execution de la requête : " + e);
        }
    }
    
    
    /**
     * @brief affiche le logo
     * @param ImageIcon image constructeur
     * @param this.setIconImage(image.getImage()) 
     * @param this.setVisible(true) affiche l'icône
     */
    //05
    private void monLogo() {
        ImageIcon image = new ImageIcon("logo.gif");
        this.setIconImage(image.getImage());
        this.setVisible(true);
    }
    /**
      * @brief Créer et déclare le groupe bouton
      * @param jRTVA4.setSelected(true) coché à l'ouverture de l'application
      */
    //06
    /**
      * @brief choix de la coche
      * @param T
      * @param choixAction.equals("jRTVA1"))
      * @details prend la valeur du composant \a Textfield qui est coché et le
      * passe en paramètre.
      */
    //07 
    private String calcul(String T) {
        //creation et execution de la requête
         Object choix = jComboToTva.getSelectedIndex();
       Object tva = jComboToTva.getSelectedItem();
       
       if (choix.equals(0)) {
           T = tva.toString();
       }
       if (choix.equals(1)) {
           T = tva.toString();
       }
       if (choix.equals(2)) {
           T = tva.toString();
       }
       if (choix.equals(3)) {
           T = tva.toString();
       }
       if (choix.equals(4)) {
           T = tva.toString();
       }
       if (choix.equals(5)) {
           T = tva.toString();
       }
       if (choix.equals(6)) {
           T = tva.toString();
       }
       return T;
    }
    /**
     * @brief affiche la date
     * @param TVA
     * @details la passe en paramètres et au format France.
     * 
     */
     
    //09
    private String calculTVA(String TVA) {
        float toTva = Float.parseFloat(calcul(T));
        String HTaxe = MontantHT.getText();
        float ht = Float.parseFloat(HTaxe); 
        float calculTVA = ht*toTva/100; 
        TVA = String.valueOf(calculTVA);
        
        return TVA;
    }
    //09.1 
    private String calculTTC(String TTC) {
        float toTva = Float.parseFloat(calcul(T));
        String HT = MontantHT.getText();
        float ht = Float.parseFloat(HT); 
        float calculTVA = ht*toTva/100;
        float calculTTC= ht+calculTVA;
        TTC = String.valueOf(calculTTC);
        
        return TTC;
    }
    //09.2
    private String calculHT(String HT) {
        float toTva = Float.parseFloat(calcul(T));
        String TTC = MontantTTC.getText();
        float ttc = Float.parseFloat(TTC); 
        float calculHT= ttc/((toTva)/100+1);
        HT = String.valueOf(calculHT);
        
        return HT;
    }//09.3
     private String calculTVATTC(String TVAT) {
        float toTva = Float.parseFloat(calcul(T));
       // String TTaxeC = MontantTTC.getText();
        String Ht = MontantHT.getText();
        //float ttc = Float.parseFloat(TTaxeC);
        float ht = Float.parseFloat(Ht);
        float calculTVATTC = ht*(toTva/100); 
        TVAT = String.valueOf(calculTVATTC);
        System.out.println("Votre choix est TVA : "+ TVAT);
        return TVAT;
    }
    //10  
    private void appelTVA() {
       String tva = calculTVA(TVA);
       MontantTva.setText(tva);
    }
    //10.1
    private void appelTTC() {
        String ttc = calculTTC(TTC);
        MontantTTC.setText(ttc);
    }
    //10.2
    private void appelHT() {
        String ht = calculHT(HT);
        MontantHT.setText(ht);
    }
    //10.3
     private void appelTVATTC() {
       String tva = calculTVATTC(TVAT);
       MontantTva.setText(tva);
    }
    //10.4
     private void appelTvaTtc() {
        appelTVA();
        appelTTC();
    }
   
    //Remise à zéro des composants
    //11
    private void raz(){
        jComboEnseigne.removeAllItems();
        TextRs.setText("");
        TextVille.setText("");
        noteAera.setText("");
        
        jComboToTva.setSelectedItem("0");
        MontantHT.setText("0.0");
        MontantTva.setText("0.0");
        MontantTTC.setText("0.0");
        jComboModePa.setSelectedItem("Espèce");
    }
    //Remise à zéro des composants
    //12
    private void razconfig(){
        EnseiText.setText("");
        SireText.setText("");
        TvaText.setText("");
    }
  
    // affichage du nom de votre enseigne dans l'onglet gonfig log et affichage.
    //13
    private void affichageEnseigne(){
         requete = "SELECT MonEnseigne, Siret, TVARS FROM `raisonSoc`"; 
       try {
                //Connexion à la base de données              
                Connection con = SourceDonneesSqlite.getConnection();
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(requete);    
                while (rs.next()) {
                A.setText(rs.getString(1));  
                B.setText(rs.getString(2));
                C.setText(rs.getString(3));
                }
            rs.close();
        } catch (Exception e) {
            System.out.println("Erreur:Anomalie lors de l'execution de la requête : " + e);
        }
       
   }
    //15
    public boolean getDonnees(){
        return true;
    }
     
    // Début pour afficher dans les jtable
    //16
    private void ouverture_jtable1() {
        Connection con = SourceDonneesSqlite.getConnection();
        String sql = "select * from recu";
       try {
            Statement stmt = con.createStatement(); //ne pas mettre de ResultSet
            ResultSet rs = stmt.executeQuery(sql);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
        } catch (Exception e) {
            System.out.println("Erreur:Anomalie lors de l'execution de la requête : " + e);
        }
    }
    //16.1
    private void ouverture_jtable2() {
        Connection con = SourceDonneesSqlite.getConnection();
        String sql = "select * from recu";
       try {
            Statement stmt = con.createStatement(); //ne pas mettre de ResultSet
            ResultSet rs = stmt.executeQuery(sql);
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
        } catch (Exception e) {
            System.out.println("Erreur:Anomalie lors de l'execution de la requête : " + e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }
    
    /**
     * Fonctions SQL 
     * 
     */
    // Affichage des taux de TVA par requete
     private void lancerTauxTVA(){   
      //   affichageDesTauxTvaReq196();
      //   affichageDesTauxTvaReq7();
      //   affichageDesTauxTvaReq55();
     }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField B;
    private javax.swing.JTextField C;
    private com.toedter.calendar.JYearChooser ChooserAnnee;
    private javax.swing.JTextField EnseiText;
    private javax.swing.JFormattedTextField MontantHT;
    private javax.swing.JFormattedTextField MontantTTC;
    private javax.swing.JFormattedTextField MontantTva;
    private javax.swing.JTextField SireText;
    private javax.swing.JFormattedTextField Stotaltva196;
    private javax.swing.JFormattedTextField Stotaltva55;
    private javax.swing.JFormattedTextField Stotaltva7;
    private javax.swing.JFormattedTextField TVA1;
    private javax.swing.JFormattedTextField TVA10;
    private javax.swing.JFormattedTextField TVA11;
    private javax.swing.JFormattedTextField TVA12;
    private javax.swing.JFormattedTextField TVA2;
    private javax.swing.JFormattedTextField TVA3;
    private javax.swing.JFormattedTextField TVA4;
    private javax.swing.JFormattedTextField TVA5;
    private javax.swing.JFormattedTextField TVA6;
    private javax.swing.JFormattedTextField TVA7;
    private javax.swing.JFormattedTextField TVA8;
    private javax.swing.JFormattedTextField TVA9;
    private javax.swing.JTextField TextRs;
    private javax.swing.JTextField TextVille;
    private javax.swing.JTextField TvaText;
    private javax.swing.JTextField TxtRecherche;
    private javax.swing.JButton ValiderBtn;
    private javax.swing.ButtonGroup groupeBtn;
    private javax.swing.JButton jBMaj;
    private javax.swing.JButton jBValider;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboDesi;
    private javax.swing.JComboBox jComboEnse;
    private javax.swing.JComboBox jComboEnseigne;
    private javax.swing.JComboBox jComboModePa;
    private javax.swing.JComboBox jComboRecherche;
    private javax.swing.JComboBox jComboToTva;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelHaut;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JFormattedTextField jformaIdRecu;
    private javax.swing.JTextArea noteAera;
    private javax.swing.JFormattedTextField tvaAnnuel;
    // End of variables declaration//GEN-END:variables
}
